services:
  website:
    build: .
    env_file:
      - .env
    command: >
      uvicorn
      --host 0.0.0.0
      --port 8000
      --reload
      "main:app"
    ports:
      - "5000:8000"
    volumes:
      - web_game_data:${DATA_VOLUME_PATH}
volumes:
  web_game_data:
    external: true
